# Generated by Django 3.0.1 on 2020-04-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30)),
                ('fatherName', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('classes', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=30)),
            ],
        ),
    ]
