# Generated by Django 3.0.1 on 2020-04-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('FeMale', 'FeMale')], max_length=30, null=True),
        ),
    ]
