# Generated by Django 3.0.1 on 2020-04-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0002_computer_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='classes',
            new_name='degree',
        ),
        migrations.AddField(
            model_name='computer',
            name='year',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('II', 'III')], max_length=30, null=True),
        ),
    ]
