# Generated by Django 3.0.1 on 2020-04-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0003_auto_20200422_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='pin',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='degree',
            field=models.CharField(choices=[(None, 'Select Degree'), ('BA', 'BA'), ('BSC', 'BSC'), ('BCOM', 'BCOM'), ('MA', 'MA'), ('MSC', 'MSC'), ('MCOM', 'MCOM')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='dept',
            field=models.CharField(choices=[(None, 'Select Department'), ('TAMIL', 'TAMIL'), ('ENGLISH', 'ENGLISH'), ('MATHS', 'MATHS'), ('CS', 'CS'), ('COMMERCE', 'COMMERCE')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='gender',
            field=models.CharField(choices=[(None, 'Select Gender'), ('Male', 'Male'), ('FeMale', 'FeMale')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='year',
            field=models.CharField(choices=[(None, 'Select Year'), ('I', 'I'), ('II', 'II'), ('II', 'III')], max_length=30, null=True),
        ),
    ]
